---
title: 예외처리
---

## 예외의 처리

```python
>>> def main():
	print("AA")
	age=int(input())
	print(age)
	print("HI")
>>> main()
AA
efe #값의 입력이 정수가 아닌 문자로 이루어져버림. (예외발생)
Traceback (most recent call last):
  File "<pyshell#72>", line 1, in <module>
    main()
  File "<pyshell#70>", line 3, in main
    age=int(input())
ValueError: invalid literal for int() with base 10: 'efe'

# ValueError라는 에러가 발생!
```

해당 예외를 처리하려면 어떻게 해야할까?

**함수의 흐름에 try영역과 except영역을 추가한다**

```python
def main():
    print("HI!")
    try:
        age=int(input("나이 입력:"))
        print("입력한 나이:") # try영역
    except ValueError:
        print("잘못된 입력") #잘못된 값 입력에 대한 예외 처리 (except영역)

    print("종료")
```

위의 코드를 보면 except영역에 ValueError라고 써져 있는 것을 볼 수 있는데, 이는 ValueError에 대해서만 예외처리를 하겠다는 뜻이다.

위와 같이 ValueError를 명시했지만 이외의 예외가 발생했을 시 해당 에러를 출력하고 프로그램은 종료된다.

## 적극적인 예외처리

입력하는 과정에서 값의 형태가 맞지 않아 예외가 발생했다면 그대로 종료할 것이 아니라 **재입력의 기회를 주는 것**이 적극적인 예외처리라고 할 수 있음.

무한루프 내에 예외처리를 하여 예외 발생 시 계속해서 재입력 할 수 있게 하고, 예외가 발생하지 않았으면 break문으로 탈출하게끔 구현

## 둘 이상의 예외 처리

except영역을 그냥 추가하면 됨. (Error에 대한 명시와 함께)

```python
def main():
    bread=10
    try:
        people = int(input("몇 명:"))
        print("인당 빵의 수: ",bread/people)
        print("빵 먹기!")
    except ValueError:
        print("입력 오류:")
    except ZeroDivisionError:
        print("0으로 나눌수는 없습니다")
```

## 예외 메세지 출력하기와 finally

```python
def main():
    bread=10
    try:
        people = int(input("몇 명:"))
        print("인당 빵 몇개: ", bread/people)
        print("빵 먹기 시작!")
    except ValueError as msg: # 변수 msg에 에러 메세지가 담김
        print("입력 오류")
        print(msg)
    except ZeroDivisionError as msg: # 변수 msg에 에러 메세지가 담김
        print("0으로 나눌수는 없다")
        print(msg)

main()
```

위의 코드에서 people값으로 0이 전달될 경우 ZeroDivisionError 예외가 발생하며 print("빵 먹기 시작!") 코드는 실행되지 않는다.

만약 해당 코드가 예외가 발생하더라도 결국 실행되어야만 하는 코드라면?

```python
# 위의 코드에 finally영역을 추가한다.
# . . . . . . . . .
finally:
    print("어쨌든 이 코드는 실행해야됨! ")
```

## 모든 예외 무시하기

```python
def main():
    bread = 10
    try:
        people=int(input("사람 수 입력:"))
        print("두당 빵 수 :", bread/people)
    except: #예외에 대한 특별한 명시 없음
        print("뭔지는 몰라도 예외가 발생!")
```

except영역에 특정 예외에 대한 명시가 없으면 모든 예외가 걸려들어 처리되게된다.

except: pass 를 통해 아무 행위도 안하면서 예외 처리를 할 수도 있긴하다..
